# Generated by Django 4.0.1 on 2022-03-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='waranty',
            new_name='warranty',
        ),
    ]
