# Generated by Django 4.0.1 on 2022-03-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='full_name',
            field=models.CharField(default='newadmin', max_length=100),
        ),
        migrations.AddField(
            model_name='admin',
            name='image',
            field=models.ImageField(default=1, upload_to='admins'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='mobile',
            field=models.CharField(default='', max_length=20),
        ),
    ]
