# Generated by Django 4.0.1 on 2022-06-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0013_alter_productupload_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='return_policy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty',
        ),
        migrations.RemoveField(
            model_name='productupload',
            name='product',
        ),
        migrations.AlterField(
            model_name='productupload',
            name='customer',
            field=models.CharField(max_length=100),
        ),
    ]
