# Generated by Django 4.0.1 on 2022-06-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0014_remove_product_return_policy_remove_product_warranty_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
