# Generated by Django 4.0.1 on 2022-06-26 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0018_remove_product_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductUpload',
        ),
    ]
