# Generated by Django 4.0.1 on 2022-06-26 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0019_delete_productupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
