# Generated by Django 4.0.1 on 2022-06-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0022_remove_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.TextField(default='Admin', max_length=20),
        ),
    ]
