# Generated by Django 4.0.1 on 2022-06-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0023_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
