# Generated by Django 4.0.1 on 2022-06-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0024_remove_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(max_length=13),
        ),
    ]
