# Generated by Django 4.0.1 on 2022-06-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0026_alter_contact_email_alter_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.TextField(default='Admin', max_length=30),
        ),
    ]
