# Generated by Django 4.0.1 on 2022-06-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0027_alter_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.TextField(default='Book Trekker', max_length=30),
        ),
    ]
