# Generated by Django 3.2.5 on 2022-06-29 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0028_alter_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='movie',
            new_name='books',
        ),
    ]
